In [2]:
import norms
import networks
from pprint import pprint
import torch
import numpy as np
import torchvision.models as models
import data_loader
from solver import load_solver
# for auto-reloading external modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

In [3]:
trainings_set = data_loader.get_CIFAR10_dataloader(True, 1000, 8, True, subset_size=50000)

Loading trainings set: cifar10, Batch size: 1000, Subset size: 50000, Random labels: False
Files already downloaded and verified

********************************************************************************



In [4]:
# net = networks.ExampleNet()
# net = models.vgg16(pretrained=True)
# net = networks.vgg16()

net = load_solver(folder='Seminar', verbose=False).model


layers = net.state_dict()
pprint(layers)

OrderedDict([('features.0.weight',
              tensor([[[[-0.0726, -0.1326,  0.0453],
          [ 0.1030,  0.0691,  0.0158],
          [ 0.0114,  0.1260, -0.1089]],

         [[-0.0785, -0.0358, -0.0125],
          [ 0.0737,  0.0539, -0.0753],
          [-0.0279,  0.0725, -0.0414]],

         [[ 0.0689, -0.0537,  0.0302],
          [ 0.1314,  0.0146, -0.0633],
          [-0.1050,  0.1222, -0.1765]]],


        [[[ 0.1306,  0.0969, -0.0061],
          [ 0.0391,  0.0288, -0.0091],
          [-0.0657,  0.0144, -0.0406]],

         [[ 0.1213,  0.0103, -0.0531],
          [-0.1997, -0.0004, -0.0089],
          [-0.0144, -0.1317, -0.0451]],

         [[ 0.1293,  0.0111, -0.0691],
          [ 0.0189,  0.0419,  0.0492],
          [-0.1024, -0.0245,  0.0829]]],


        [[[ 0.0667,  0.0320, -0.0070],
          [-0.2026, -0.0461, -0.0461],
          [-0.0091,  0.0092, -0.0375]],

         [[ 0.0429, -0.0348, -0.2005],
          [ 0.0609, -0.1232, -0.0870],
          [-0.0035,  0.0596,  0.0152

              tensor([[[[ 1.4294e-02,  1.5854e-02,  1.0338e-02],
          [-4.9212e-02, -2.1499e-02, -5.5905e-03],
          [-5.8739e-02, -1.9519e-02, -2.5539e-02]],

         [[-1.8125e-02,  5.6953e-03,  4.8278e-03],
          [-3.2159e-02,  2.9651e-02,  5.5559e-02],
          [-2.3400e-02, -1.6107e-03,  9.4189e-03]],

         [[-5.1092e-03,  8.0931e-03,  4.4415e-02],
          [ 1.1439e-02, -5.9421e-03,  8.2346e-04],
          [-5.5892e-02, -4.7790e-02, -2.6131e-02]],

         ...,

         [[-1.1468e-02,  1.2616e-02,  1.7821e-02],
          [ 1.7225e-02,  2.9700e-02,  3.0467e-02],
          [-5.7247e-02, -1.8481e-02, -1.7937e-02]],

         [[ 1.3131e-02,  3.8826e-02,  3.1328e-02],
          [ 1.9217e-02,  4.1300e-02,  5.3796e-02],
          [ 5.4086e-02,  4.5068e-02,  3.8768e-02]],

         [[-2.3574e-02, -1.6449e-02, -2.8258e-02],
          [-2.3061e-02, -4.9120e-02, -3.4140e-02],
          [-4.5872e-02, -8.9957e-02, -6.5299e-02]]],


        [[[-3.1727e-02, -3.0843e-02, -1

              tensor([-9.4821e-02, -2.2778e-41,  7.6727e-02,  1.4054e-02,  7.8606e-03,
        -9.3245e-02, -5.7030e-41, -6.6636e-02, -3.1767e-42,  2.7855e-02,
        -3.4252e-03, -6.4025e-02, -6.1909e-42, -4.8494e-02, -2.1146e-41,
         2.3742e-02, -2.4390e-41,  9.7511e-02,  8.8556e-02, -5.0822e-41,
         9.9780e-03,  9.6141e-02,  6.3790e-02, -4.5919e-41,  6.2414e-02,
        -3.8778e-41, -3.3417e-41, -4.6780e-41,  4.0320e-02,  4.8247e-02,
         1.2014e-01, -1.9254e-41,  5.4649e-02, -7.2630e-02, -2.5279e-41,
         4.4592e-02, -1.8963e-02, -1.6466e-02,  5.4206e-02, -6.0009e-41,
        -1.6760e-42,  6.5152e-02,  6.3272e-02, -6.9027e-02,  6.9325e-02,
        -5.1295e-02,  1.0859e-02, -2.8618e-02,  4.6271e-02,  5.4162e-02,
        -4.3132e-42, -4.1883e-02, -4.5490e-41,  1.0381e-01,  6.8949e-02,
        -4.5755e-03, -4.7830e-02, -6.3394e-02, -3.8038e-03,  1.0224e-01,
        -6.4754e-42, -7.8052e-43,  7.5587e-02,  1.1438e-02, -2.0219e-41,
         1.0731e-01, -2.1305e-41, -1.

              tensor([-4.2455e-41,  4.2064e-41,  5.2329e-41,  1.2445e-07,  3.6868e-42,
        -2.1979e-41,  1.0926e-07,  4.3620e-41, -2.6330e-42,  1.7438e-08,
         1.4943e-07,  9.7525e-08,  1.8410e-07, -6.9714e-08, -4.9895e-41,
         5.6963e-41,  2.4908e-41, -3.5398e-08,  1.9509e-41,  6.0823e-41,
        -3.3107e-41, -3.8163e-41,  1.2274e-41, -2.6737e-08,  2.5470e-41,
         6.0661e-41, -5.6164e-41,  4.5382e-41, -5.2477e-41,  5.5532e-41,
         1.6580e-41,  3.8729e-41,  2.8888e-08, -4.2318e-41,  4.3098e-08,
        -3.8592e-42, -4.8205e-43, -1.9300e-41, -2.3149e-42, -6.7515e-42,
         1.9083e-41,  5.0988e-41,  7.0065e-42, -3.0614e-41,  3.5356e-41,
         2.1318e-08, -5.8203e-41, -1.2458e-41,  2.1709e-07,  1.9828e-08,
        -2.3421e-41, -2.5723e-08,  8.0785e-42, -1.2180e-41, -8.3950e-08,
        -8.7198e-09, -1.2191e-41, -7.0079e-42,  2.5392e-41, -1.6115e-41,
         6.5160e-42, -2.5434e-08, -4.1759e-41,  4.0521e-41, -2.1762e-41,
        -5.8818e-41,  2.3454e-41, -2.

             ('features.31.running_var',
              tensor([7.1984e-02, 5.6052e-45, 1.3336e+00, 9.6353e-01, 3.4606e-02, 5.6052e-45,
        5.6052e-45, 5.6052e-45, 1.4599e+00, 5.6052e-45, 1.8369e+00, 5.6052e-45,
        5.8549e-01, 5.6052e-45, 4.7837e-02, 2.8801e-01, 5.6052e-45, 1.1169e+00,
        7.0323e-01, 1.1768e+00, 5.6052e-45, 5.6052e-45, 4.2988e-01, 1.6259e+00,
        5.6052e-45, 5.6052e-45, 5.6052e-45, 5.6052e-45, 5.6052e-45, 2.0682e+00,
        9.7849e-01, 3.0580e-01, 5.6052e-45, 5.6052e-45, 5.6052e-45, 2.6855e+00,
        5.6052e-45, 5.6052e-45, 5.6052e-45, 5.6052e-45, 3.6041e+00, 2.9137e-01,
        1.0138e+00, 9.0877e-02, 4.0353e-01, 7.8634e-01, 4.2453e-01, 5.6052e-45,
        5.6052e-45, 1.1444e+00, 5.6052e-45, 5.3036e-02, 5.6052e-45, 7.4409e-01,
        5.5147e+00, 8.5483e-01, 6.9979e-01, 5.6052e-45, 5.6052e-45, 5.6052e-45,
        5.6052e-45, 5.6052e-45, 5.6052e-45, 1.4029e+00, 5.6052e-45, 1.1613e+00,
        8.9078e-02, 5.6052e-45, 5.6052e-45, 1.3783e+00, 5.6052e-4

             ('features.38.bias',
              tensor([-4.7291e-02, -4.7107e-41, -1.2673e-01, -1.9922e-41, -4.2032e-41,
        -1.0291e-01, -1.3712e-01, -5.0081e-02, -3.5628e-02, -3.3513e-41,
        -8.1002e-02, -8.6815e-02, -2.8414e-02, -8.7445e-02, -3.4831e-02,
        -1.0410e-01, -1.2681e-01, -1.1327e-01, -2.7802e-41, -4.0926e-41,
        -8.0225e-02, -1.0518e-01, -9.2379e-02,  1.0404e-02, -3.3208e-02,
        -1.0168e-01, -8.5595e-02, -3.9691e-02,  1.9079e-03, -8.8954e-02,
        -5.8292e-02,  1.9469e-02, -8.1015e-02, -1.2739e-01,  3.8340e-02,
        -1.5058e-01,  4.1332e-02, -1.6544e-01, -1.4969e-01, -1.0060e-01,
        -7.9449e-02, -8.3034e-02, -4.5070e-02, -1.0937e-01, -3.8375e-02,
        -4.1376e-41, -9.4301e-02, -7.8926e-02,  9.7576e-03,  1.1416e-02,
        -1.3311e-03,  2.4857e-02, -7.7301e-02, -5.1494e-41, -3.8623e-02,
        -1.9561e-41, -1.5422e-01, -1.1158e-01, -4.0807e-03, -1.0681e-01,
        -1.3259e-01, -1.2454e-01, -2.7194e-03, -2.2014e-03, -1.5319e-02,
   

         1.9446e-02,  7.7297e-03], device='cuda:0')),
             ('classifier.4.weight',
              tensor([[-0.0026, -0.0030,  0.0004,  ...,  0.0126, -0.0033,  0.0177],
        [-0.0077, -0.0072,  0.0067,  ...,  0.0132,  0.0298, -0.0039],
        [-0.0042, -0.0014,  0.0056,  ...,  0.0035, -0.0106, -0.0071],
        ...,
        [-0.0188, -0.0028, -0.0017,  ..., -0.0221, -0.0083,  0.0223],
        [ 0.0666,  0.0017,  0.0045,  ...,  0.0183,  0.0203, -0.0035],
        [-0.0042,  0.0008,  0.0032,  ..., -0.0165,  0.0125, -0.0056]],
       device='cuda:0')),
             ('classifier.4.bias',
              tensor([-2.8675e-02, -4.4268e-02, -1.0262e-01, -1.2002e-02, -2.9663e-02,
        -9.2021e-02, -9.9327e-02, -9.7339e-04,  9.5420e-05, -1.4451e-03,
        -7.6247e-02,  1.3340e-03,  3.9701e-01, -8.3537e-02, -2.9228e-02,
         1.8717e-01,  4.6516e-03,  1.2351e-04, -7.5772e-02, -5.3691e-02,
        -4.9596e-04, -2.3079e-02, -7.5346e-03,  5.3746e-03, -1.1623e-02,
         2.8754e-01, 

# Norms

In [7]:
net = load_solver(folder='Seminar', filename='solver_e50.pth', verbose=False).model
l2 = norms.l2_norm(net, trainings_set, 0.05)
print(l2)

Processing layer features.0.weight
Processing layer features.0.bias
Skipping features.0.bias
Processing layer features.1.weight
Processing layer features.1.bias
Skipping features.1.bias
Processing layer features.1.running_mean
Skipping features.1.running_mean
Processing layer features.1.running_var
Skipping features.1.running_var
Processing layer features.1.num_batches_tracked
Skipping features.1.num_batches_tracked
Processing layer features.3.weight
Processing layer features.3.bias
Skipping features.3.bias
Processing layer features.4.weight
Processing layer features.4.bias
Skipping features.4.bias
Processing layer features.4.running_mean
Skipping features.4.running_mean
Processing layer features.4.running_var
Skipping features.4.running_var
Processing layer features.4.num_batches_tracked
Skipping features.4.num_batches_tracked
Processing layer features.7.weight
Processing layer features.7.bias
Skipping features.7.bias
Processing layer features.8.weight
Processing layer features.8.bias

In [8]:
spectral = norms.spectral_norm(net, trainings_set, 0.05)
print(spectral)

Processing layer features.0.weight
Layer features.0.weight has no norm. (64, 3, 3, 3)
Processing layer features.0.bias
Skipping features.0.bias
Processing layer features.1.weight
Processing layer features.1.bias
Skipping features.1.bias
Processing layer features.1.running_mean
Skipping features.1.running_mean
Processing layer features.1.running_var
Skipping features.1.running_var
Processing layer features.1.num_batches_tracked
Skipping features.1.num_batches_tracked
Processing layer features.3.weight
Layer features.3.weight has no norm. (64, 64, 3, 3)
Processing layer features.3.bias
Skipping features.3.bias
Processing layer features.4.weight
Processing layer features.4.bias
Skipping features.4.bias
Processing layer features.4.running_mean
Skipping features.4.running_mean
Processing layer features.4.running_var
Skipping features.4.running_var
Processing layer features.4.num_batches_tracked
Skipping features.4.num_batches_tracked
Processing layer features.7.weight
Layer features.7.weigh

In [ ]:
nuclear_norm = norms.norm_product(layers, 'nuc')
print(nuclear_norm)

In [ ]:
#inf_norm = norms.norm_product(layers, np.linalg.norm, 'inf')
#print(inf_norm)

In [ ]:
#min_inf_norm = norms.norm_product(layers, np.linalg.norm, '-inf')
#print(min_inf_norm)

In [ ]:
#abs_norm = norms.norm_product(layers, np.linalg.norm, 0)
#print(abs_norm)

In [ ]:
l1_norm = norms.norm_product(layers, 1)
print(l1_norm)

In [ ]:
min_abs_norm = norms.norm_product(layers, -1)
print(min_abs_norm)

In [ ]:
min_singular_norm = norms.norm_product(layers, -2)
print(max_singular_norm)